'use strict';
const scenes=window.VR_SCENES,$=id=>document.getElementById(id),canvas=$('view'),stage=$('stage');
const gl=canvas.getContext('webgl',{alpha:false,antialias:true,xrCompatible:true});
const rad=Math.PI/180,clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),wrap=x=>((x+180)%360+360)%360-180;
let current=0,loadedSlug='',textures=[],ready=false,allReady=false,loadId=0,yaw=0,pitch=0,auto=false,autoSign=1,autoDistance=0;
let availableRange=0,nextPrefetchTimer=null;const pendingImages=new Set(),prefetchedFronts=new Set();
let gyro=false,gyroOrigin=null,gyroTarget=null,gyroTimer=null,split=false,xrSession=null,xrRef=null,xrOrigin=null,last=0,disposed=false;
const minZoom=.8,maxZoom=2;
const sourceAspect=1672/941,safeVerticalTangent=Math.cos(15*rad)/sourceAspect*.98;
let zoom=1;
// Old QR codes have auto=1; the scene-first interface defaults to manual exploration.
let startAutoWhenReady=new URLSearchParams(location.search).get('autoplay')==='1';
const menu=$('tour-menu');let hintTimer=null;
menu.addEventListener('click',e=>{if(['gyro','xr'].includes(e.target.id))closeMenu()},{capture:true});
function closeMenu(){if(menu.open)menu.close()}
$('menu-toggle').onclick=()=>{stopAuto();menu.showModal()};$('menu-close').onclick=closeMenu;
menu.addEventListener('click',e=>{if(e.target!==menu)return;const r=menu.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeMenu()});
function hideHint(){clearTimeout(hintTimer);$('gesture-hint').classList.add('dismissed')}
const sceneRoutes={
 entrance:[['overview','进入营地']],overview:[['service','服务中心'],['parking','房车营位'],['kitchen','天幕聚餐']],
 service:[['shower_interior','淋浴间'],['reception_interior','进入接待'],['kitchen_interior','共享厨房']],
 parking:[['camp_pad_detail','进入营位'],['hookups','水电接口'],['overview','返回营地']],
 kitchen:[['kitchen_interior','进入厨房'],['service','服务中心']],charging:[['overview','返回营地'],['parking','前往营位']],
 hookups:[['camp_pad_detail','营位细节'],['parking','返回营位']],edge:[['lakeside_walk','湖畔步道'],['overview','返回营地']],
 reception_interior:[['market_interior','驻车集超市'],['service','回到广场']],market_interior:[['laundry_interior','洗衣房'],['service','回到广场']],
 laundry_interior:[['shower_interior','淋浴间'],['service','回到广场']],kitchen_interior:[['kitchen','天幕聚餐'],['service','回到广场']],
 shower_interior:[['accessible_interior','卫生间'],['service','回到广场']],accessible_interior:[['shower_interior','淋浴间'],['service','回到广场']],
 lakeside_walk:[['edge','周边配套'],['overview','返回营地']],camp_pad_detail:[['hookups','水电接口'],['parking','返回营位']]
};
function sceneLinks(slug){$('scene-links').replaceChildren();for(const [target,label] of sceneRoutes[slug]||[]){const b=document.createElement('button');b.dataset.scene=target;b.disabled=true;b.setAttribute('aria-label',label);b.innerHTML='<svg viewBox="0 0 44 44" aria-hidden="true"><ellipse cx="22" cy="27" rx="18" ry="12"/><path d="m14 25 8-8 8 8m-8-7v18" fill="none"/></svg>';const text=document.createElement('span');text.textContent=label;b.append(text);b.onclick=()=>{hideHint();showScene(scenes.findIndex(s=>s.slug===target))};$('scene-links').append(b)}}
function viewAspect(){return Math.max(1,canvas.clientWidth)/Math.max(1,canvas.clientHeight)/(split?2:1)}
function baseVerticalTangent(aspect){return Math.min(Math.tan(29*rad)/aspect,Math.tan((split?29:aspect<1.4?26:16)*rad))}
function viewLimits(){const baseTy=baseVerticalTangent(viewAspect()),zoomFloor=Math.max(minZoom,baseTy/safeVerticalTangent);return{zoomFloor,pitchLimit:Math.max(0,Math.min(12,(Math.atan(safeVerticalTangent)-Math.atan(baseTy/Math.max(zoom,zoomFloor)))/rad))}}
function updateZoom(){const floor=viewLimits().zoomFloor;$('zoom-level').textContent=Math.round(zoom*100)+'%';$('zoom-out').disabled=!!xrSession||zoom<=floor+.00001;$('zoom-in').disabled=!!xrSession||zoom>=maxZoom;$('zoom-reset').disabled=!!xrSession||Math.abs(zoom-Math.max(1,floor))<.001}
function setZoom(value){if(xrSession)return;zoom=clamp(value,viewLimits().zoomFloor,maxZoom);stopAuto();updateUI()}
const stats={frames:0,sceneCommits:0,errors:[],xrFrames:0};
function message(text){$('message').textContent=text}
function fail(e){stats.errors.push(String(e.message||e));message(String(e.message||e))}
if(!gl){message('浏览器不支持WebGL，请使用此前的普通巡游版');throw Error('WebGL unavailable')}
function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
function program(fragment){const p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,'attribute vec2 position;varying vec2 v;void main(){v=position;gl_Position=vec4(position,0.,1.);}'));gl.attachShader(p,shader(gl.FRAGMENT_SHADER,fragment));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p}
const photoProgram=program(`precision highp float;
varying vec2 v;uniform sampler2D t0,t1,t2,t3,t4,t5,t6;uniform mat3 rotation;uniform mat4 inverseProjection;uniform bool xrMode,frontOnly;uniform vec2 tangent;uniform float yawOffset,availableRange;
void main(){vec3 r;if(xrMode){vec4 p=inverseProjection*vec4(v,1.,1.);vec3 w=rotation*normalize(p.xyz/p.w);r=vec3(w.x,w.y,-w.z);}else r=rotation*vec3(v.x*tangent.x,v.y*tangent.y,1.);
float c=cos(yawOffset),s=sin(yawOffset);r=vec3(c*r.x+s*r.z,r.y,-s*r.x+c*r.z);
float angle=atan(r.x,r.z),degrees=angle*57.2957795;float b=frontOnly?0.:clamp(floor(degrees/30.+.5)*30.,-availableRange,availableRange);float a=b*.0174532925;float z=sin(a)*r.x+cos(a)*r.z;vec2 q=vec2(.5+.5*(cos(a)*r.x-sin(a)*r.z)/z,.5+.5*r.y*(1672./941.)/z);
if(z<=0.||q.x<0.||q.x>1.||q.y<0.||q.y>1.){float g=pow(max(0.,1.-abs(r.y)/length(r)),4.);gl_FragColor=vec4(vec3(.025,.07,.095)+vec3(.015,.035,.04)*g,1.);return;}
vec4 color;if(b< -75.)color=texture2D(t0,q);else if(b< -45.)color=texture2D(t1,q);else if(b< -15.)color=texture2D(t2,q);else if(b<15.)color=texture2D(t3,q);else if(b<45.)color=texture2D(t4,q);else if(b<75.)color=texture2D(t5,q);else color=texture2D(t6,q);gl_FragColor=color;}`);
const hudProgram=program('precision mediump float;varying vec2 v;uniform sampler2D hud;void main(){if(v.y>-.65||abs(v.x)>.78)discard;vec2 q=vec2((v.x/.78+1.)*.5,(-v.y-.65)/.35);gl_FragColor=texture2D(hud,q);}');
const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);
function bindProgram(p){gl.useProgram(p);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);const loc=gl.getAttribLocation(p,'position');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0)}
const locations=Object.fromEntries(['rotation','inverseProjection','xrMode','frontOnly','tangent','yawOffset','availableRange'].map(n=>[n,gl.getUniformLocation(photoProgram,n)]));
const blank=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,blank);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,1,1,0,gl.RGB,gl.UNSIGNED_BYTE,new Uint8Array([5,17,24]));gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);
const hudCanvas=document.createElement('canvas');hudCanvas.width=1024;hudCanvas.height=170;const hudCtx=hudCanvas.getContext('2d'),hudTexture=gl.createTexture();let hudKey='';
function updateHud(){const key=loadedSlug+allReady;if(key===hudKey)return;hudKey=key;hudCtx.clearRect(0,0,1024,170);hudCtx.fillStyle='rgba(4,22,30,.9)';hudCtx.fillRect(0,0,1024,170);hudCtx.textAlign='center';hudCtx.fillStyle='#eaf9f5';hudCtx.font='bold 35px "Microsoft YaHei", sans-serif';hudCtx.fillText(scenes.find(s=>s.slug===loadedSlug)?.name||'正在载入…',512,51);hudCtx.fillStyle='#b5d9d3';hudCtx.font='23px "Microsoft YaHei", sans-serif';hudCtx.fillText('180°单目方案 · 范围外无素材 · 不支持行走',512,100);hudCtx.fillText('扳机：下一场景   侧握：回正   系统菜单：退出',512,143);gl.activeTexture(gl.TEXTURE7);gl.bindTexture(gl.TEXTURE_2D,hudTexture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,hudCanvas);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE)}
function upload(img){const tex=gl.createTexture();gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,tex);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,gl.RGB,gl.UNSIGNED_BYTE,img);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);return{tex,width:img.naturalWidth,height:img.naturalHeight}}
window.VR_ASSET_CACHE={};
function sceneAssets(scene){return new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=scene.dataScript;script.onload=()=>{const items=window.VR_ASSET_CACHE[scene.slug];delete window.VR_ASSET_CACHE[scene.slug];script.remove();items?resolve(items):reject(Error('场景数据不完整'))};script.onerror=()=>{script.remove();reject(Error('场景文件未能载入，请检查离线包是否完整'))};document.head.append(script)})}
function imageAsset(asset,id,priority='auto'){return new Promise((resolve,reject)=>{const img=new Image();img.decoding='async';img.fetchPriority=priority;const cleanup=()=>{pendingImages.delete(cancel);img.onload=null;img.onerror=null},cancel=()=>{cleanup();img.src='';resolve(null)};pendingImages.add(cancel);img.onload=()=>{cleanup();try{resolve(id===loadId?upload(img):null)}catch(e){reject(e)}};img.onerror=()=>{cleanup();id===loadId?reject(Error('图片加载失败：'+asset.base+'°')):resolve(null)};img.src=asset.data||asset.src})}
function queueNextFront(){clearTimeout(nextPrefetchTimer);const id=loadId,scene=scenes[(current+1)%scenes.length],url=scene.frontSrc;if(!url||prefetchedFronts.has(url)||navigator.connection?.saveData||/^(slow-)?2g$/.test(navigator.connection?.effectiveType||''))return;nextPrefetchTimer=setTimeout(()=>{if(id!==loadId||!auto||!allReady)return;const img=new Image();img.fetchPriority='low';img.decoding='async';img.onload=()=>prefetchedFronts.add(url);img.src=url},2500)}
function deleteTextures(items){for(const item of items)if(item)gl.deleteTexture(item.tex)}
function stopAuto(){auto=false;autoDistance=0;$('auto').setAttribute('aria-pressed','false');$('auto').textContent='自动巡游'}
function updateUI(){zoom=clamp(zoom,viewLimits().zoomFloor,maxZoom);const limit=viewLimits().pitchLimit;yaw=clamp(yaw,-availableRange,availableRange);pitch=clamp(pitch,-limit,limit);$('yaw').min=-availableRange;$('yaw').max=availableRange;$('yaw').value=yaw;$('heading').textContent=(Math.abs(yaw)<.1?'正前方':(yaw<0?'左 ':'右 ')+Math.abs(yaw).toFixed(0)+'°')+(gyro?' · 手机转头':'')+(split?' · 单目分屏':'');updateZoom()}
async function showScene(index,keepAuto=false){closeMenu();const id=++loadId;for(const cancel of [...pendingImages])cancel();clearTimeout(nextPrefetchTimer);allReady=false;availableRange=0;stage.dataset.loadingSides='true';current=(index+scenes.length)%scenes.length;const scene=scenes[current];sceneLinks(scene.slug);if(!keepAuto)stopAuto();yaw=0;pitch=0;gyroOrigin=null;gyroTarget=null;autoSign=1;autoDistance=0;$('scene').value=scene.slug;$('scene-title').textContent=scene.name;$('scene-info').textContent=scene.info;$('position').textContent=String(current+1).padStart(2,'0')+' / '+scenes.length;$('scenes').querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-pressed',String(i===current)));history.replaceState(null,'','#'+scene.slug);message('正在载入 '+scene.name+'…');updateUI();
 let next=[];try{const items=await sceneAssets(scene);if(id!==loadId)return;const front=await imageAsset(items.find(a=>a.base===0),id,'high');if(id!==loadId)return;next[3]=front;deleteTextures(textures);textures=next;ready=true;loadedSlug=scene.slug;stats.sceneCommits++;updateHud();message('');$('scene-links').querySelectorAll('button').forEach(b=>b.disabled=false);clearTimeout(hintTimer);hintTimer=setTimeout(hideHint,6000);
 for(const range of [30,60,90]){await Promise.all(items.filter(a=>Math.abs(a.base)===range).map(async a=>{const tex=await imageAsset(a,id,range===30?'high':'low');if(id!==loadId){if(tex)gl.deleteTexture(tex.tex);return}next[(a.base+90)/30]=tex}));if(id!==loadId)return;availableRange=range;if(startAutoWhenReady){startAutoWhenReady=false;auto=true;$('auto').setAttribute('aria-pressed','true');$('auto').textContent='暂停巡游'}updateUI()}
 allReady=true;stage.dataset.loadingSides='false';message('');updateHud();queueNextFront();
 }catch(e){if(id===loadId){fail(e);stopAuto()}}
}
function rotY(a){const c=Math.cos(a),s=Math.sin(a);return[c,0,-s,0,1,0,s,0,c]}
function rotX(a){const c=Math.cos(a),s=Math.sin(a);return[1,0,0,0,c,s,0,-s,c]}
function rotZ(a){const c=Math.cos(a),s=Math.sin(a);return[c,s,0,-s,c,0,0,0,1]}
function mul3(a,b){const r=new Array(9).fill(0);for(let col=0;col<3;col++)for(let row=0;row<3;row++)for(let k=0;k<3;k++)r[col*3+row]+=a[k*3+row]*b[col*3+k];return r}
function inverse4(m){const rows=Array.from({length:4},(_,r)=>Array.from({length:8},(_,c)=>c<4?m[c*4+r]:+(c-4===r)));for(let i=0;i<4;i++){let pivot=i;for(let j=i+1;j<4;j++)if(Math.abs(rows[j][i])>Math.abs(rows[pivot][i]))pivot=j;[rows[i],rows[pivot]]=[rows[pivot],rows[i]];const p=rows[i][i];if(Math.abs(p)<1e-12)throw Error('VR投影矩阵不可逆');for(let c=0;c<8;c++)rows[i][c]/=p;for(let r=0;r<4;r++)if(r!==i){const f=rows[r][i];for(let c=0;c<8;c++)rows[r][c]-=f*rows[i][c]}}return Float32Array.from({length:16},(_,i)=>rows[i%4][4+Math.floor(i/4)])}
function render(viewport,rotation,inv=null,offset=0){gl.viewport(viewport.x,viewport.y,viewport.width,viewport.height);bindProgram(photoProgram);for(let i=0;i<7;i++){gl.activeTexture(gl.TEXTURE0+i);gl.bindTexture(gl.TEXTURE_2D,textures[i]?.tex||blank);gl.uniform1i(gl.getUniformLocation(photoProgram,'t'+i),i)}gl.uniformMatrix3fv(locations.rotation,false,new Float32Array(rotation));gl.uniform1i(locations.xrMode,!!inv);gl.uniform1i(locations.frontOnly,availableRange===0);gl.uniform1f(locations.availableRange,availableRange);gl.uniform1f(locations.yawOffset,offset);if(inv)gl.uniformMatrix4fv(locations.inverseProjection,false,inv);const aspect=viewport.width/viewport.height,ty=baseVerticalTangent(aspect)/zoom;gl.uniform2f(locations.tangent,ty*aspect,ty);gl.drawArrays(gl.TRIANGLES,0,6);if(inv){bindProgram(hudProgram);gl.activeTexture(gl.TEXTURE7);gl.bindTexture(gl.TEXTURE_2D,hudTexture);gl.uniform1i(gl.getUniformLocation(hudProgram,'hud'),7);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.drawArrays(gl.TRIANGLES,0,6);gl.disable(gl.BLEND)}}
function draw(now){if(disposed)return;requestAnimationFrame(draw);const dt=last?Math.min((now-last)/1000,.1):0;last=now;if(xrSession)return;if(ready&&availableRange>0&&auto){const move=dt*8;yaw+=autoSign*move;autoDistance+=move;if(yaw>=availableRange){yaw=availableRange;autoSign=-1}if(yaw<=-availableRange){yaw=-availableRange;autoSign=1}if(autoDistance>=360&&allReady){showScene(current+1,true)}}if(gyroTarget&&gyro){yaw+=wrap(gyroTarget.yaw-yaw)*Math.min(1,dt*12);pitch+=(gyroTarget.pitch-pitch)*Math.min(1,dt*12)}updateUI();const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.clearColor(.02,.06,.09,1);gl.clear(gl.COLOR_BUFFER_BIT);if(!ready)return;const r=mul3(rotY(yaw*rad),rotX(-pitch*rad));if(split){const half=Math.floor(w/2);render({x:0,y:0,width:half,height:h},r);render({x:half,y:0,width:w-half,height:h},r)}else render({x:0,y:0,width:w,height:h},r);stats.frames++}
let drag=null,pinch=null;const pointers=new Map();
function pointerDistance(){const [a,b]=[...pointers.values()];return Math.hypot(a.x-b.x,a.y-b.y)}
function startDrag(p){drag={x:p.x,y:p.y,yaw,pitch,zoom}}
canvas.addEventListener('pointerdown',e=>{if(!ready||xrSession||e.button>0)return;hideHint();disableGyro();stopAuto();pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);if(pointers.size===1)startDrag(pointers.get(e.pointerId));else{drag=null;if(pointers.size===2)pinch={distance:Math.max(1,pointerDistance()),zoom}}});
canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size>=2&&pinch){setZoom(pinch.zoom*pointerDistance()/pinch.distance);return}if(!drag)return;const aspect=viewAspect(),ty=baseVerticalTangent(aspect)/drag.zoom;yaw=drag.yaw+(drag.x-e.clientX)/canvas.clientWidth*2*Math.atan(ty*aspect)/rad;pitch=drag.pitch+(e.clientY-drag.y)/canvas.clientHeight*2*Math.atan(ty)/rad;updateUI()});
function endPointer(e){pointers.delete(e.pointerId);pinch=null;drag=null;if(pointers.size===1)startDrag([...pointers.values()][0]);else if(pointers.size>=2)pinch={distance:Math.max(1,pointerDistance()),zoom}}
for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,endPointer);
// Capture at the whole viewer so labels, controls and status overlays cannot swallow wheel zoom.
stage.addEventListener('wheel',e=>{if(!ready||xrSession||menu.open)return;e.preventDefault();const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?canvas.clientHeight:1);if(delta)setZoom(zoom*Math.exp(-delta*.0015))},{passive:false,capture:true});
canvas.addEventListener('keydown',e=>{if(['+','=','-','_','0'].includes(e.key)&&ready&&!xrSession){e.preventDefault();setZoom(e.key==='0'?1:zoom*(e.key==='-'||e.key==='_'?1/1.2:1.2));return}if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)||!ready)return;e.preventDefault();stopAuto();disableGyro();yaw+=e.key==='ArrowLeft'?-5:e.key==='ArrowRight'?5:0;pitch+=e.key==='ArrowUp'?3:e.key==='ArrowDown'?-3:0;updateUI()});$('yaw').oninput=()=>{stopAuto();disableGyro();yaw=Number($('yaw').value);updateUI()};
$('zoom-in').onclick=()=>setZoom(zoom*1.2);$('zoom-out').onclick=()=>setZoom(zoom/1.2);$('zoom-reset').onclick=()=>setZoom(1);updateZoom();
function recenter(){stopAuto();yaw=0;pitch=0;gyroOrigin=null;gyroTarget=null;xrOrigin=null;updateUI()}
function disableGyro(){gyro=false;gyroOrigin=null;gyroTarget=null;clearTimeout(gyroTimer);$('gyro').setAttribute('aria-pressed','false');$('gyro').textContent='手机转头'}
function deviceAngles(event){const a=event.alpha,b=event.beta,g=event.gamma;if(![a,b,g].every(Number.isFinite))return null;const screenAngle=(screen.orientation?.angle??window.orientation??0)*rad;let m=mul3(mul3(rotY(a*rad),rotX(b*rad)),rotZ(-g*rad));m=mul3(mul3(m,rotX(-Math.PI/2)),rotZ(-screenAngle));return{yaw:Math.atan2(-m[6],m[8])/rad,pitch:Math.asin(clamp(-m[7],-1,1))/rad}}
addEventListener('deviceorientation',e=>{if(!gyro)return;const p=deviceAngles(e);if(!p)return;clearTimeout(gyroTimer);if(!gyroOrigin)gyroOrigin=p;gyroTarget={yaw:clamp(wrap(p.yaw-gyroOrigin.yaw),-90,90),pitch:clamp(p.pitch-gyroOrigin.pitch,-12,12)};message('')});
$('gyro').onclick=async()=>{if(gyro){disableGyro();message('');return}try{if(!isSecureContext)throw Error('手机转头需要安全访问环境，请使用HTTPS版；仍可手指拖动');if(!window.DeviceOrientationEvent)throw Error('此设备没有可用的方向传感器，请使用拖动');if(typeof DeviceOrientationEvent.requestPermission==='function'){const permission=await DeviceOrientationEvent.requestPermission();if(permission!=='granted')throw Error('未获传感器权限，仍可手指拖动')}stopAuto();gyro=true;gyroOrigin=null;gyroTarget=null;$('gyro').setAttribute('aria-pressed','true');$('gyro').textContent='关闭手机转头';message('请转动手机，舒适姿势下可点回正/校准');gyroTimer=setTimeout(()=>{if(!gyroOrigin){disableGyro();message('没有收到传感器数据，已恢复拖动模式')}},6000)}catch(e){disableGyro();message(e.message)}};
function immersiveUI(value){document.body.classList.toggle('immersive',value);$('exit-full').hidden=!value;$('fullscreen').setAttribute('aria-pressed',String(value));$('fullscreen').textContent=value?'退出系统全屏':'系统全屏'}
async function enterFull(){immersiveUI(true);if(!document.fullscreenElement&&stage.requestFullscreen)try{await stage.requestFullscreen()}catch(e){message('已进入沉浸布局；浏览器未允许系统全屏')}}
async function exitFull(){if(document.fullscreenElement)try{await document.exitFullscreen()}catch(e){}immersiveUI(false);if(split)setSplit(false)}
$('fullscreen').onclick=()=>{closeMenu();document.body.classList.contains('immersive')?exitFull():enterFull()};$('exit-full').onclick=exitFull;addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement){immersiveUI(false);if(split)setSplit(false)}});addEventListener('keydown',e=>{if(e.key==='Escape'&&!xrSession&&!menu.open)exitFull()});
function setSplit(value){split=value;stage.classList.toggle('split',split);$('split').setAttribute('aria-pressed',String(split));$('split').textContent=split?'退出分屏':'眼镜分屏';updateUI()}
$('split').onclick=async()=>{closeMenu();stopAuto();setSplit(!split);if(split){await enterFull();if(innerHeight>innerWidth)message('请横放手机。左右显示相同单目画面，无真实景深')}else message('')};
$('center').onclick=()=>{recenter();closeMenu()};$('prev').onclick=()=>showScene(current-1);$('next').onclick=()=>showScene(current+1);$('scene').onchange=()=>showScene(scenes.findIndex(s=>s.slug===$('scene').value));$('auto').onclick=()=>{if(auto){stopAuto();return}if(!ready||availableRange===0){message('正面载入后即可观看，正在补齐附近视野…');closeMenu();return}closeMenu();disableGyro();auto=true;autoDistance=0;autoSign=yaw>=availableRange?-1:1;$('auto').setAttribute('aria-pressed','true');$('auto').textContent='暂停巡游';message('');queueNextFront()};
function cameraRotation(m){return[m[0],m[1],m[2],m[4],m[5],m[6],m[8],m[9],m[10]]}
function xrFrame(now,frame){const session=frame.session;if(session!==xrSession)return;session.requestAnimationFrame(xrFrame);const pose=frame.getViewerPose(xrRef);if(!pose||!ready)return;const m=pose.transform.matrix;if(xrOrigin===null)xrOrigin=Math.atan2(-m[8],m[10]);const layer=session.renderState.baseLayer;gl.bindFramebuffer(gl.FRAMEBUFFER,layer.framebuffer);gl.clearColor(.02,.06,.09,1);gl.clear(gl.COLOR_BUFFER_BIT);for(const view of pose.views){render(layer.getViewport(view),cameraRotation(view.transform.matrix),inverse4(view.projectionMatrix),-xrOrigin)}stats.xrFrames++}
async function endXR(){if(xrSession)await xrSession.end()}
$('xr').onclick=async()=>{if(xrSession){await endXR();return}if(!allReady){message('请等待两侧视野加载完成再进入VR');return}let session=null;try{stopAuto();disableGyro();setSplit(false);session=await navigator.xr.requestSession('immersive-vr');await gl.makeXRCompatible();if(disposed){await session.end();return}xrRef=await session.requestReferenceSpace('local').catch(()=>session.requestReferenceSpace('viewer'));session.updateRenderState({baseLayer:new XRWebGLLayer(session,gl,{alpha:false,antialias:true})});xrOrigin=null;xrSession=session;$('xr').textContent='退出VR头显';$('xr').setAttribute('aria-pressed','true');message('');session.addEventListener('end',()=>{xrSession=null;xrRef=null;xrOrigin=null;gl.bindFramebuffer(gl.FRAMEBUFFER,null);$('xr').textContent='进入VR头显';$('xr').setAttribute('aria-pressed','false');message('已退出VR，可继续拖动观看')},{once:true});session.addEventListener('select',()=>showScene(current+1));session.addEventListener('squeeze',recenter);session.requestAnimationFrame(xrFrame)}catch(e){if(session)try{await session.end()}catch(ignore){}xrSession=null;xrRef=null;$('xr').textContent='进入VR头显';$('xr').setAttribute('aria-pressed','false');message('VR未能启动：'+e.message+'。仍可沉浸全屏观看')}};
async function capabilities(){const secure=isSecureContext?'安全环境':'非安全环境';let supported=false;try{supported=!!(isSecureContext&&navigator.xr&&await navigator.xr.isSessionSupported('immersive-vr'))}catch(e){}$('xr').disabled=!supported;$('xr').textContent=supported?'进入VR头显':'此设备无VR头显';$('capability').textContent=secure+' · '+(supported?'检测到WebXR沉浸VR支持':'未检测到WebXR沉浸VR支持，可使用拖动/全屏/分屏')+'。传感器和头显实机效果需在实际设备上验证。'}
scenes.forEach((s,i)=>{const o=new Option(String(i+1).padStart(2,'0')+' · '+s.name,s.slug);$('scene').add(o);const b=document.createElement('button');b.textContent=s.name;b.onclick=()=>showScene(i);$('scenes').append(b)});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();ready=false;allReady=false;stopAuto();message('图形上下文已丢失，请刷新页面重新载入')});
addEventListener('pagehide',()=>{disposed=true;loadId++;clearTimeout(nextPrefetchTimer);clearTimeout(hintTimer);for(const cancel of [...pendingImages])cancel();disableGyro();deleteTextures(textures);if(xrSession)xrSession.end().catch(()=>{})});
window.VR_DEBUG={state:()=>({current,loadedSlug,ready,allReady,availableRange,yaw,pitch,zoom,viewLimits:viewLimits(),auto,gyro,split,xr:!!xrSession,textures:textures.map(t=>t&&[t.width,t.height]),stats}),setAngles:(y,p=0)=>{stopAuto();yaw=y;pitch=p;updateUI()},next:()=>showScene(current+1),inverse4,deviceAngles,render,gl};
const initial=scenes.findIndex(s=>s.slug===location.hash.slice(1));showScene(initial<0?scenes.findIndex(s=>s.slug==='entrance'):initial).catch(fail);capabilities();requestAnimationFrame(draw);
